name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # adjust to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'  # specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        env:
          API_KEY: ${{ secrets.API_KEY }}  # access the API_KEY secret
        run: |
          export API_KEY="${API_KEY}"  # set the API_KEY environment variable

      - name: Deploy application
        run: |
          streamlit run nemotron-app.py
